include(include_guard)
include_guard(__included_all)

include(utils)
include(message)
include(settings)
include(ccache)
include(compile_flags)
include(default_build)
include(dependencies)
include(version)

include(project)
include(module)
include(find_lib)
include(bin)
include(lib)
include(protoc)
include(test)
include(install)
include(install_makefile)
