include(include_guard)
include_guard(__included_all)

include(settings)
include(ccache)
include(compile_flags)
include(default_build)
include(dependencies)
include(version)

include(module)
include(bin)
include(qt)
include(qt_bin)
include(lib)
include(test)