#!/bin/bash

for variant in debug release
do
    echo "[ Generating ${variant} makefiles ]"
    mkdir -p .build/${variant}
    pushd .build/${variant} > /dev/null
    cmake -Dbuild=${variant} ../..
    popd > /dev/null
done
